services:
  - type: web
    name: retwit-server
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false 